[platformio]
default_envs = poll_status

[env]
platform = espressif32
framework = arduino
board = esp32dev
lib_extra_dirs = .
lib_deps =
    bblanchon/ArduinoJson @ ^7
build_flags =
    -Wall
    -Wextra

[env:discovery]
src_dir = examples
build_src_filter = -<*> +<discovery.ino>

[env:poll_status]
src_dir = examples
build_src_filter = -<*> +<poll_status.ino>

[env:control_relay]
src_dir = examples
build_src_filter = -<*> +<control_relay.ino>
