[platformio]
default_envs = poll_status
src_dir = platformio_src

[env]
platform = espressif32
framework = arduino
board = esp32-c3-devkitm-1
lib_extra_dirs = .
extra_scripts =
    pre:scripts/load_env.py
lib_deps =
    bblanchon/ArduinoJson @ ^7
build_flags =
    -Wall
    -Wextra
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:discovery]
build_src_filter = -<*> +<discovery.cpp>

[env:poll_status]
build_src_filter = -<*> +<poll_status.cpp>

[env:push_updates]
build_src_filter = -<*> +<push_updates.cpp>

[env:async_fsm]
build_src_filter = -<*> +<async_fsm.cpp>

[env:multi_device]
build_src_filter = -<*> +<multi_device.cpp>

[env:control_relay]
build_src_filter = -<*> +<control_relay.cpp>

[env:board_smoke]
build_src_filter = -<*> +<board_smoke.cpp>
