#pragma once

#include "example_wifi_config.h"

#ifndef TINYTUYA_DEVICE_ID
#define TINYTUYA_DEVICE_ID "DEVICE_ID_HERE"
#endif

#ifndef TINYTUYA_DEVICE_IP
#define TINYTUYA_DEVICE_IP "192.168.1.42"
#endif

#ifndef TINYTUYA_LOCAL_KEY
#define TINYTUYA_LOCAL_KEY "0123456789abcdef"
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION
#define TINYTUYA_PROTOCOL_VERSION 3.3
#endif

#ifndef TINYTUYA_RELAY_DP
#define TINYTUYA_RELAY_DP 1
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_2
#define TINYTUYA_PROTOCOL_VERSION_2 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_3
#define TINYTUYA_PROTOCOL_VERSION_3 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_4
#define TINYTUYA_PROTOCOL_VERSION_4 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_5
#define TINYTUYA_PROTOCOL_VERSION_5 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_6
#define TINYTUYA_PROTOCOL_VERSION_6 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_7
#define TINYTUYA_PROTOCOL_VERSION_7 TINYTUYA_PROTOCOL_VERSION
#endif

#ifndef TINYTUYA_PROTOCOL_VERSION_8
#define TINYTUYA_PROTOCOL_VERSION_8 TINYTUYA_PROTOCOL_VERSION
#endif
