from pathlib import Path

Import("env")

ROOT = Path(env["PROJECT_DIR"])
ENV_FILE = ROOT / ".env"
OUT_FILE = ROOT / "include" / "tinytuya_env.h"


def parse_env(path):
    values = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


values = parse_env(ENV_FILE)
OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

lines = [
    "#pragma once",
    "",
    "/* Generated by scripts/load_env.py from local .env. Do not commit. */",
]

if "WIFI_SSID" in values:
    lines.append(f"#define TINYTUYA_WIFI_SSID {c_string(values['WIFI_SSID'])}")
if "WIFI_PASS" in values:
    lines.append(f"#define TINYTUYA_WIFI_PASS {c_string(values['WIFI_PASS'])}")

OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
