from pathlib import Path

Import("env")

ROOT = Path(env["PROJECT_DIR"])
ENV_FILE = ROOT / ".env"
OUT_FILE = ROOT / "include" / "tinytuya_env.h"


def parse_env(path):
    values = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def c_string(value):
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return '"' + escaped + '"'


values = parse_env(ENV_FILE)
OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

lines = [
    "#pragma once",
    "",
    "/* Generated by scripts/load_env.py from local .env. Do not commit. */",
]

string_keys = {
    "WIFI_SSID": "TINYTUYA_WIFI_SSID",
    "WIFI_PASS": "TINYTUYA_WIFI_PASS",
    "TUYA_DEVICE_ID": "TINYTUYA_DEVICE_ID",
    "TUYA_DEVICE_IP": "TINYTUYA_DEVICE_IP",
    "TUYA_LOCAL_KEY": "TINYTUYA_LOCAL_KEY",
    "FORWARD_SERVER_URL": "TINYTUYA_FORWARD_SERVER_URL",
    "FORWARD_TLS_HOSTNAME": "TINYTUYA_FORWARD_TLS_HOSTNAME",
    "FORWARD_TOKEN": "TINYTUYA_FORWARD_TOKEN",
}

for index in range(2, 9):
    string_keys[f"TUYA_DEVICE_ID_{index}"] = f"TINYTUYA_DEVICE_ID_{index}"
    string_keys[f"TUYA_DEVICE_IP_{index}"] = f"TINYTUYA_DEVICE_IP_{index}"
    string_keys[f"TUYA_LOCAL_KEY_{index}"] = f"TINYTUYA_LOCAL_KEY_{index}"

for env_key, define_name in string_keys.items():
    if env_key in values:
        lines.append(f"#define {define_name} {c_string(values[env_key])}")

if "FORWARD_CA_CERT_FILE" in values:
    cert_path = Path(values["FORWARD_CA_CERT_FILE"])
    if not cert_path.is_absolute():
        cert_path = ROOT / cert_path
    cert = cert_path.read_text(encoding="utf-8")
    if "-----BEGIN CERTIFICATE-----" not in cert:
        raise ValueError(f"Invalid CA certificate: {cert_path}")
    lines.append(f"#define TINYTUYA_FORWARD_CA_CERT {c_string(cert)}")

numeric_keys = {
    "TUYA_PROTOCOL_VERSION": "TINYTUYA_PROTOCOL_VERSION",
    "TUYA_RELAY_DP": "TINYTUYA_RELAY_DP",
    "FORWARD_INTERVAL_MS": "TINYTUYA_FORWARD_INTERVAL_MS",
}

for index in range(2, 9):
    numeric_keys[f"TUYA_PROTOCOL_VERSION_{index}"] = f"TINYTUYA_PROTOCOL_VERSION_{index}"

for env_key, define_name in numeric_keys.items():
    if env_key in values:
        lines.append(f"#define {define_name} {values[env_key]}")

OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
